apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "dell-sno1"
  namespace: "dell-sno1"
spec:
  baseDomain: "product-int.example.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.15.0-x86-64-appsub"
  sshPublicKey: "ssh-rsa KEYHERE"
  clusters:
  - clusterName: "dell-sno1"
    clusterLabels:
      # Placement Rule Labels for policy binding 
      logicalGroup: "active"
      common-415: "true"
      group-du-sno: ""
      sites : "product-int.example.com"
      vendor: "OpenShift"
      flexran: "timer-mode"
      du-profile: "seed"
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    machineNetwork:
      - cidr: "10.0.0.0/24"
    serviceNetwork:
      - "172.30.0.0/16"
    networkType: "OVNKubernetes"
    additionalNTPSources:
      - "clock.redhat.com"
    cpuPartitioningMode: AllNodes
    nodes:
      - hostName: "dell-sno1.oob.product-int.example.com"
        role: "master"
        bmcAddress: "idrac-virtualmedia://10.6.0.84/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "dell-sno1-worker"
        bootMACAddress: "7C:C2:55:99:BE:EF"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/sda"
        nodeNetwork:
          interfaces:
            - name: "eno1np0"
              macAddress: "7C:C2:55:99:BE:EF"
          config:
            interfaces:
            - name: eno1np0
              type: ethernet
              state: up
              ipv4:
                address:
                  - ip: 10.0.0.31 
                    prefix-length: 24
                dhcp: false
                enabled: true
              ipv6:
                dhcp: false
                autoconf: false
                enabled: false
            dns-resolver:
              config:
                server:
                - 10.0.0.2
                - 10.0.0.1 
            routes:
              config:
                - destination: '0.0.0.0/0'
                  next-hop-address: '10.0.0.254'
                  next-hop-interface: eno1np0
